# Generated by Django 3.1.3 on 2021-04-17 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='measurement_unit',
            field=models.CharField(choices=[(1, 'Bori'), (2, 'Kg'), (3, 'unit')], default='Choose measurement unit', max_length=255),
        ),
    ]
