# Generated by Django 3.1.3 on 2021-04-17 12:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0002_stock_measurement_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 4, 17, 12, 22, 1, 601102, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='measurement_unit',
            field=models.CharField(choices=[('un', 'unit'), ('kg', 'kg'), ('br', 'bori')], default='Choose measurement unit', max_length=255),
        ),
    ]
