# Generated by Django 3.1.5 on 2021-04-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0005_stockhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhistory',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
