# Generated by Django 3.1.5 on 2021-04-21 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0006_auto_20210419_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='user',
        ),
    ]
